DATA SEGMENT               
DATA1 DB 019H,0BCH,0E2H,08H 
DATA2 DW 19BCH, 0E208H , 0008H
DATA ENDS


CODE SEGMENT 
ASSUME CS:CODE, DS:DATA

START: 
MOV AX , DATA
MOV DS , AX    

;IMMEDIATE ADDRESSING MODE  
MOV AX , DATA2  
MOV AL , DATA1  
                
; REGISTER ADDRESSING MODE
MOV BX , AX
MOV BL , AL

; DIRECT ADDRESSING MODE

MOV AX , [0005H]
MOV BX , [0100H]

; REGISTER INDIRECT ADDRESSING MODE
MOV DI , OFFSET DATA1
MOV BX , OFFSET DATA2
MOV AX , [BX]        
MOV AL , [DI]

;INDEXED ADDRESSING MODE 

MOV DI , 02H
MOV SI , 06H
MOV AL , [DI+2]
MOV AX , [SI + 04H] 

;BASED ADDRESSING MODE

;MOV BP , DATA1
MOV AL , [BP + 0200H]

;BASE INDEXED ADDRESSING MODE 
                   
MOV BX , OFFSET DATA2
MOV DI , OFFSET DATA1                   
MOV AX , [BX + DI]

;BASED INDEXED DISPLACEMENT MODE 
MOV AL , [SI+BP + 0300H]

;EXIT PROGRAM
MOV AH , 4CH
INT 21H
CODE ENDS
END START

     

